// src/components/sectionGroupItem.tsx
import * as React from 'react';
import SectionItem from './sectionItem';

class SectionGroupItem extends React.Component<{sectionGroup: OneNoteApi.SectionGroup}, null> {
	render() {
		return (
			<li>
				<a className={'is-active'}>{this.props.sectionGroup.name}</a>
				<ul>
					{this.props.sectionGroup.sectionGroups.map(sectionGroup => <SectionGroupItem sectionGroup={sectionGroup} key={sectionGroup.name}></SectionGroupItem>)}
					{this.props.sectionGroup.sections.map(section => <SectionItem section={section} key={section.name}></SectionItem>)}
				</ul>
			</li>
		);
	}
}

export default SectionGroupItem;

// src/components/sectionGroupItem.vue
<template>
    <li>
        <a class="is-active" @click="selectSectionGroup(sectionGroup.id)">{{ sectionGroup.name }}</a>
        <ul>
			<section-group-item v-for="group in sectionGroup.sectionGroups" :key="group" :section-group="group"></section-group-item>
            <section-item v-for="section in sectionGroup.sections" :key="section" :section="section"></section-item>
        </ul>
    </li>
</template>

<script lang="ts">
    import Vue from "vue";
    import Component from "vue-class-component";

    import SectionItem from "./sectionItem.vue";

    @Component({
        name: "section-group-item",
        components: { SectionItem },
        props: {
            sectionGroup: { required: true },
        }
    })

    export default class SectionGroupItem extends Vue {
		selectSectionGroup(sectionGroupId: string): void {
            this.$store.dispatch('selectSectionGroup', sectionGroupId);
        }
    }
</script>
