// src/oneNotePicker.vue
<template>
	<ul class="menu-list">
		<notebook-item v-for="notebook in notebooks" :key="notebook" :notebook="notebook"></notebook-item>
	</ul>
</template>

<script lang="ts">
import Vue from "vue";
import Component from "vue-class-component";

import NotebookItem from "./components/notebookItem.vue";

@Component({
	name: "onenote-picker",
	components: { "notebook-item": NotebookItem },
	props: {
		notebooks: { required: true }
	}
})

export default class OneNotePicker extends Vue {
}
</script>

// src/oneNotePicker.tsx
import * as React from 'react';
import NotebookItem from './components/notebookItem';

class OneNotePicker extends React.Component<{ notebooks: OneNoteApi.Notebook[] }, null> {
	render() {
		return (
			<ul className={'menu-list'}>
				{this.props.notebooks.map(notebook => <NotebookItem notebook={notebook} key={notebook.name}></NotebookItem>)}
			</ul>
		);
	}
}

export default OneNotePicker;
